### ISSUE TITLE
NN probabilities greater than 1.

### ISSUE THREAD

**Issue by kstawiski** [jpmml/openscoring#15]
Dear Villu,
My issue is the continuation of #14.
I have few more neural networks I would like to score and gain probability measures.
Here I put my PMML files:
[Ovaries-NNqPCR2.txt](https://github.com/jpmml/openscoring/files/417142/Ovaries-NNqPCR2.txt)
[Ovaries-NNKeller.txt](https://github.com/jpmml/openscoring/files/417143/Ovaries-NNKeller.txt)

For example one can receive the following output:
`{   "id" : "Qz2XDQoJ5HiF7jmc4GDn",   "result" : {     "ID_REF" : "Controls+Borderline",     "probability_disease" : -0.4489425455522529,     "probability_no_disease" : 1.3847227148467958   } }`
The output probabilities turned out by these networks doesn't sum up to 1 and I'm not able to find a reason for this phenomena.
Is there a next issue with PMML files or I missed something in the construction of the network?

Thank you very much for your help in advance.

Best regards,
Konrad

**Comment by vruusmann** [comment]
You need to use some other NN training software (such as R, Scikit-Learn, KNIME, RapidMiner etc.), because your current software - "STATISTICA Automated Neural Networks (SANN), version 2.0" - is generating invalid PMML documents.

The case in point is the `NormContinuous` element. SANN is adding `shift` and `scale` to it, which are not part of the [PMML schema version 3.0 specification] (http://dmg.org/pmml/v3-0/Transformations.html)).

You can use the `org.jpmml.model.ValidationExample` command-line application from the [JPMML-Model] (https://github.com/jpmml/jpmml-model) project to perform static validation of PMML files:
```
java -cp pmml-model-example/target/example-1.3-SNAPSHOT.jar org.jpmml.model.ValidationExample --input Ovaries-NNKeller.txt 
```

The validation application will print all warnings and errors to console. Here is what it has to say about SANN generated `NormContinuous` elements:
```
SEVERE: [severity=FATAL_ERROR,message=cvc-complex-type.3.2.2: Attribute 'shift' is not allowed to appear in element 'NormContinuous'.,locator=[node=null,object=null,url=null,line=35,col=182,offset=-1]]
SEVERE: [severity=FATAL_ERROR,message=cvc-complex-type.3.2.2: Attribute 'scale' is not allowed to appear in element 'NormContinuous'.,locator=[node=null,object=null,url=null,line=35,col=182,offset=-1]]
```
